structure(list(url = "http://127.0.0.1:8001/api/expression/export/?regulator_symbol=HAP5&source_time=mcisaac_oe%2C15", 
    status_code = 200L, headers = structure(list(date = "Thu, 20 Jun 2024 17:58:51 GMT", 
        server = "uvicorn", `content-type` = "text/csv", `content-disposition` = "attachment; filename=\"Expression.csv.gz\"", 
        vary = "Accept, Accept-Language, Cookie, origin", allow = "GET, HEAD, OPTIONS", 
        `x-frame-options` = "DENY", `content-length` = "632", 
        `content-language` = "en", `x-content-type-options` = "nosniff", 
        `referrer-policy` = "same-origin", `cross-origin-opener-policy` = "same-origin"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 301L, version = "HTTP/1.1", 
        headers = structure(list(date = "Thu, 20 Jun 2024 17:58:51 GMT", 
            server = "uvicorn", `content-type` = "text/html; charset=utf-8", 
            location = "/api/expression/export/?regulator_symbol=HAP5&source_time=mcisaac_oe%2C15", 
            vary = "Accept-Language, origin", `content-language` = "en", 
            `x-content-type-options` = "nosniff", `referrer-policy` = "same-origin", 
            `cross-origin-opener-policy` = "same-origin", `transfer-encoding` = "chunked"), class = c("insensitive", 
        "list"))), list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(date = "Thu, 20 Jun 2024 17:58:51 GMT", 
            server = "uvicorn", `content-type` = "text/csv", 
            `content-disposition` = "attachment; filename=\"Expression.csv.gz\"", 
            vary = "Accept, Accept-Language, Cookie, origin", 
            allow = "GET, HEAD, OPTIONS", `x-frame-options` = "DENY", 
            `content-length` = "632", `content-language` = "en", 
            `x-content-type-options` = "nosniff", `referrer-policy` = "same-origin", 
            `cross-origin-opener-policy` = "same-origin"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("id,uploader_id,upload_date,modifier_id,modified_date,regulator_id,batch,strain,replicate,control,mechanism,restriction,time,source_id,file,notes\n5027,1,2024-03-18,1,2024-03-18 20:41:29.746203+00:00,1348,undefined,undefined,1,undefined,undefined,undefined,0.0,4,expression/hu_reimann_tfko/5027.csv.gz,none\n4563,1,2024-03-18,1,2024-03-18 19:55:53.119625+00:00,1348,undefined,SMY2076,1,undefined,zev,P,15.0,6,expression/mcisaac_oe/4563.csv.gz,strain_id:SMY2076 ; date:20160321\n1344,1,2024-03-18,1,2024-03-18 18:40:07.609714+00:00,1348,undefined,undefined,1,undefined,undefined,undefined,0.0,5,expression/kemmeren_tfko/1344.csv.gz,none\n"), 
    date = structure(1718906331, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0.036676, namelookup = 8.2e-05, 
    connect = 8.2e-05, pretransfer = 0.000219, starttransfer = 0.118652, 
    total = 0.11878)), class = "response")
