structure(list(url = "http://127.0.0.1:8001/", status_code = 200L, 
    headers = structure(list(date = "Tue, 11 Jun 2024 22:01:13 GMT", 
        server = "uvicorn", `content-type` = "text/html; charset=utf-8", 
        `x-frame-options` = "DENY", `content-length` = "3468", 
        vary = "Accept-Language, Cookie", `content-language` = "en", 
        `x-content-type-options` = "nosniff", `referrer-policy` = "same-origin", 
        `cross-origin-opener-policy` = "same-origin"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(date = "Tue, 11 Jun 2024 22:01:13 GMT", 
            server = "uvicorn", `content-type` = "text/html; charset=utf-8", 
            `x-frame-options` = "DENY", `content-length` = "3468", 
            vary = "Accept-Language, Cookie", `content-language` = "en", 
            `x-content-type-options` = "nosniff", `referrer-policy` = "same-origin", 
            `cross-origin-opener-policy` = "same-origin"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw(""), date = structure(1718143273, class = c("POSIXct", 
    "POSIXt"), tzone = "GMT"), times = c(redirect = 0, namelookup = 6.3e-05, 
    connect = 0.000139, pretransfer = 0.000174, starttransfer = 0.063396, 
    total = 0.063442)), class = "response")
