structure(list(url = "http://127.0.0.1:8001/api/expression/", 
    status_code = 200L, headers = structure(list(date = "Thu, 20 Jun 2024 18:01:49 GMT", 
        server = "uvicorn", `content-type` = "application/json", 
        vary = "Accept, Accept-Language, Cookie, origin", allow = "GET, POST, HEAD, OPTIONS", 
        `x-frame-options` = "DENY", `content-length` = "47816", 
        `content-language` = "en", `x-content-type-options` = "nosniff", 
        `referrer-policy` = "same-origin", `cross-origin-opener-policy` = "same-origin"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 301L, version = "HTTP/1.1", 
        headers = structure(list(date = "Thu, 20 Jun 2024 18:01:49 GMT", 
            server = "uvicorn", `content-type` = "text/html; charset=utf-8", 
            location = "/api/expression/", vary = "Accept-Language, origin", 
            `content-language` = "en", `x-content-type-options` = "nosniff", 
            `referrer-policy` = "same-origin", `cross-origin-opener-policy` = "same-origin"), class = c("insensitive", 
        "list"))), list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(date = "Thu, 20 Jun 2024 18:01:49 GMT", 
            server = "uvicorn", `content-type` = "application/json", 
            vary = "Accept, Accept-Language, Cookie, origin", 
            allow = "GET, POST, HEAD, OPTIONS", `x-frame-options` = "DENY", 
            `content-length` = "47816", `content-language` = "en", 
            `x-content-type-options` = "nosniff", `referrer-policy` = "same-origin", 
            `cross-origin-opener-policy` = "same-origin"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw(""), date = structure(1718906509, class = c("POSIXct", 
    "POSIXt"), tzone = "GMT"), times = c(redirect = 0.077008, 
    namelookup = 0.000209, connect = 0.00029, pretransfer = 0.000447, 
    starttransfer = 0.2123, total = 0.2125)), class = "response")
